
# very BIG NOTE that i need to put here
# this config will download everything inside a "userdata" folder
# "userdata" folder will have another folder called "models" and "ui"
# "models" will have your models downloaded to it
# "ui" will have some your webui element
# for "ui" it will be explained in the webui section
#
# if you don't understand how YAML BLOCK SEQUENCE work its recommended for you read some tutorial for it
#
# default template for most part
# - name: (file name.safetensors / file name.pt / file name.ckpt etc)
#   url: (file url)
#
# you can copy the template as many as you want for example
# - name: model1.safetensors
#   url: http://example.com/model1
# - name: model2.pt
#   url: http://example.com/model2
#
common:
  models:
    - name: AOM3_orangemixs.safetensors
      url: https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/Models/AbyssOrangeMix3/AOM3_orangemixs.safetensors
    - name: animagine-xl-2.0.safetensors
      url: https://huggingface.co/Linaqruf/animagine-xl-2.0/resolve/main/animagine-xl-2.0.safetensors
  vae:
    - name: sdxl_vae.safetensors
      url: https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors
    - name: vae-ft-mse-840000-ema-pruned.safetensors
      url: https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors
    - name: Anything-V3.0.vae.pt
      url: https://huggingface.co/Enzage/vaev3/resolve/main/Anything-V3.0.vae.pt
  lora:
    # - name:
    #   url:
  embeddings:
    - name: NegMutation-500.pt
      url: https://huggingface.co/tolerantpancake/NegativeMutation/resolve/main/NegMutation-500.pt
    - name: NegLowRes-2400.pt
      url: https://huggingface.co/tolerantpancake/NegativeLowResolution/resolve/main/NegLowRes-2400.pt
    - name: EasyNegative.pt
      url: https://huggingface.co/embed/negative/resolve/main/EasyNegative.pt
    - name: EasyNegativeV2.safetensors
      url: https://huggingface.co/embed/negative/resolve/main/EasyNegativeV2.safetensors
    - name: bad-artist-anime.pt
      url: https://huggingface.co/embed/negative/resolve/main/bad-artist-anime.pt
    - name: bad-artist.pt
      url: https://huggingface.co/embed/negative/resolve/main/bad-artist.pt
    - name: bad-hands-5.pt
      url: https://huggingface.co/embed/negative/resolve/main/bad-hands-5.pt
    - name: bad-image-v2-39000.pt
      url: https://huggingface.co/embed/negative/resolve/main/bad-image-v2-39000.pt
    - name: bad_prompt_version2.pt
      url: https://huggingface.co/embed/negative/resolve/main/bad_prompt_version2.pt
    - name: ng_deepnegative_v1_75t.pt
      url: https://huggingface.co/embed/negative/resolve/main/ng_deepnegative_v1_75t.pt
    - name: verybadimagenegative_v1.3.pt
      url: https://huggingface.co/embed/negative/resolve/main/verybadimagenegative_v1.3.pt
  hypernetwork:
    # - name:
    #   url:
  controlnet:
    - name: control_v11e_sd15_ip2p_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11e_sd15_ip2p_fp16.safetensors
    - name: control_v11e_sd15_shuffle_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11e_sd15_shuffle_fp16.safetensors
    - name: control_v11p_sd15_canny_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_canny_fp16.safetensors
    - name: control_v11f1p_sd15_depth_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11f1p_sd15_depth_fp16.safetensors
    - name: control_v11p_sd15_inpaint_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_inpaint_fp16.safetensors
    - name: control_v11p_sd15_lineart_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_lineart_fp16.safetensors
    - name: control_v11p_sd15_mlsd_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_mlsd_fp16.safetensors
    - name: control_v11p_sd15_normalbae_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_normalbae_fp16.safetensors
    - name: control_v11p_sd15_openpose_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_openpose_fp16.safetensors
    - name: control_v11p_sd15_scribble_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_scribble_fp16.safetensors
    - name: control_v11p_sd15_seg_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_seg_fp16.safetensors
    - name: control_v11p_sd15_softedge_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_softedge_fp16.safetensors
    - name: control_v11p_sd15s2_lineart_anime_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15s2_lineart_anime_fp16.safetensors
    - name: control_v11f1e_sd15_tile_fp16.safetensors
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11f1e_sd15_tile_fp16.safetensors
    - name: control_v11e_sd15_ip2p_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11e_sd15_ip2p_fp16.yaml
    - name: control_v11e_sd15_shuffle_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11e_sd15_shuffle_fp16.yaml
    - name: control_v11p_sd15_canny_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_canny_fp16.yaml
    - name: control_v11f1p_sd15_depth_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11f1p_sd15_depth_fp16.yaml
    - name: control_v11p_sd15_inpaint_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_inpaint_fp16.yaml
    - name: control_v11p_sd15_lineart_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_lineart_fp16.yaml
    - name: control_v11p_sd15_mlsd_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_mlsd_fp16.yaml
    - name: control_v11p_sd15_normalbae_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_normalbae_fp16.yaml
    - name: control_v11p_sd15_openpose_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_openpose_fp16.yaml
    - name: control_v11p_sd15_scribble_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_scribble_fp16.yaml
    - name: control_v11p_sd15_seg_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_seg_fp16.yaml
    - name: control_v11p_sd15_softedge_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15_softedge_fp16.yaml
    - name: control_v11p_sd15s2_lineart_anime_fp16.yaml
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/control_v11p_sd15s2_lineart_anime_fp16.yaml
    - name: t2iadapter_style_sd14v1.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_style_sd14v1.pth
    - name: t2iadapter_sketch_sd14v1.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_sketch_sd14v1.pth
    - name: t2iadapter_seg_sd14v1.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_seg_sd14v1.pth
    - name: t2iadapter_openpose_sd14v1.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_openpose_sd14v1.pth
    - name: t2iadapter_keypose_sd14v1.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_keypose_sd14v1.pth
    - name: t2iadapter_depth_sd14v1.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_depth_sd14v1.pth
    - name: t2iadapter_color_sd14v1.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_color_sd14v1.pth
    - name: t2iadapter_canny_sd14v1.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_canny_sd14v1.pth
    - name: t2iadapter_canny_sd15v2.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_canny_sd15v2.pth
    - name: t2iadapter_depth_sd15v2.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_depth_sd15v2.pth
    - name: t2iadapter_sketch_sd15v2.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_sketch_sd15v2.pth
    - name: t2iadapter_zoedepth_sd15v1.pth
      url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/t2iadapter_zoedepth_sd15v1.pth
sd:
  # this is a section for stable diffusion webui
  # "ui" folder will have this structure
  #
  # ui
  # `-- sd
  #     |-- extensions
  #     |   `-- .
  #     |-- models
  #     |   `-- .
  #     |-- outputs
  #     |   `-- .
  #     |-- scripts
  #     |   `-- .
  #     |-- config.json
  #     `-- ui-config.json
  #
  # in case you want to add something to stable diffusion, e.g custom script
  # put it here
  #
  # for models folder, only download here if its not covered in common section
  # e.g sam model for segment anything extensions
  # ---------------------------------------
  #
  # extensions use git to download
  #
  # git template
  # - name: (folder name/repo name)
  #   url: (repo url)
  #   branch: (branch name OPTIONAL)
  #   commit: (commit hash OPTIONAL)
  #
  # example
  # - name: extension1
  #   url: https://example.com/gituser/extension1
  # - name: extension2
  #   url: https://example.com/gituser/extension2
  #   branch: dev
  #
  # branch and commit are optional
  # if not present then will download the latest commit on the main branch
  #
  # oh yea controlnet will be installed whether you want it or not (even if you don't include it)
  extensions:
    - name: sd-webui-tunnels
      url: https://github.com/Bing-su/sd-webui-tunnels
    - name: sd-webui-controlnet
      url: https://github.com/Mikubill/sd-webui-controlnet
    - name: sd-webui-civbrowser
      url: https://github.com/SignalFlagZ/sd-webui-civbrowser
    - name: a1111-sd-webui-tagcomplete
      url: https://github.com/DominikDoom/a1111-sd-webui-tagcomplete
    - name: sd-webui-infinite-image-browsing
      url: https://github.com/zanllp/sd-webui-infinite-image-browsing
    - name: adetailer
      url: https://github.com/Bing-su/adetailer
    - name: ultimate-upscale-for-automatic1111
      url: https://github.com/Coyote-A/ultimate-upscale-for-automatic1111
  #
  # custom_download same as name url format but with dir
  #
  # example
  # - dir: models/sam
  #   name: sam_model.pth
  #   url: https://example.com/sam_model.pth
  #
  # do remember, dir will always "ui" folder subdirectory
  # so, with the example above it will download to ui/sd/models/sam/sam_model.pth
  #
  # if you happen to put absolute / full path e.g /root/somedir, it will download to a warning folder in "ui" folder
  #
  # this is useful when you want to download extra models but its not covered in common section
  #
  custom_download:
    - dir: models/ESRGAN
      name: 4x-UltraSharp.pth
      url: https://huggingface.co/embed/upscale/resolve/main/4x-UltraSharp.pth
    - dir: models/ESRGAN
      name: 4x-AnimeSharp.pth
      url: https://huggingface.co/konohashinobi4/4xAnimesharp/resolve/main/4x-AnimeSharp.pth
    # - dir:
    #   name:
    #   url:
  #
  # if you want to use your pre-configured config.json or ui-config.json
  # you can put the json download url here
  #
  # by doing this, you can reduce the amount of time need to setup the webui to your liking
  #
  config_json:
  ui_config_json:
  #
  # env stand for Environment
  # args stand for Arguments
  # both env and args are using this template
  # - (a text)
  #
  # for example
  # - EXAMPLE_ENV=examplevalue
  # - --example-arg examplevalue
  #
  # please see https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings
  # for more explain about what env and arg can be used
  #
  env:
    # - --EXAMPLE_ENV=examplevalue
  args:
    - --no-half-vae
    - --no-download-sd-model
    - --no-hashing
    - --opt-sdp-attention
    - --enable-insecure-extension-access
    - --disable-safe-unpickle
    # - --example-arg examplevalue
